Fixes, Enhancements and Refactoring
BishopFox/pwn-pulse pull request #2
Opened 2019-10-20 19:17 UTC by bl4ckh0l3z

#### Fixes:
- The tool stops if the VPN service version is not recognized, and files are removed
- Don't print cached VPN client session details if [[username and password] or lastlogin] fields are blank (false positive reduction!)
- Discard cached VPN client session details if username or pw contain a string ending with "+" (false positive reduction!)
- Managing the escape of '\n' for egreps
- Managing the case of a target provided twice, e.g. by domain and IP at the same time

#### Enhancements:
- For each cached VPN client session extract additional info from authentication details - such as operating system, mac address, language and interal IP address
- Exploits multiple targets through the -t flag and provided in csv format or by a file
- Exploitation tests can be chosen by flags (-d/download, -c/cookie test, -s/extract ssh keys, -a/all)
- Minor changes to table formating for the final report

#### Refactoring:
- Creating functions for a more readable code
- Output files are saved into a single folder for each target
- Reorganizing the final report file

2019-12-01 14:58 UTC, braindead-bf commented
Very nice work here! I reviewed the changes and for the most part they are great improvements. When I try to test the code, however, it fails to run:
```
$ curl https://raw.githubusercontent.com/BishopFox/pwn-pulse/7207f018e58e3cd4bb8b4a2f9244510ed2bd79ec/pwn-pulse.sh -o pwn-pulse2.sh
$ ./pwn-pulse2.sh -h
./pwn-pulse2.sh: line 388: syntax error near unexpected token `;;'
./pwn-pulse2.sh: line 388: `              ;;'
```
I took a look at the code and didn't see any obvious errors that would cause this. Can you have a look?

2019-12-01 18:34 UTC, bl4ckh0l3z commented
Happy to hear that; it's a quite strange error...because everything looks fine for me...

`curl https://raw.githubusercontent.com/BishopFox/pwn-pulse/7207f018e58e3cd4bb8b4a2f9244510ed2bd79ec/pwn-pulse.sh -o pwn-pulse3.sh && sudo chmod +x ./pwn-pulse3.sh && ./pwn-pulse3.sh -h`

![scree1](https://user-images.githubusercontent.com/8762278/69918344-07074b80-1471-11ea-9fed-e0fabddc11fd.png)

I re-tested the script and it works like a charm on my side. 

![screen2](https://user-images.githubusercontent.com/8762278/69918380-7c731c00-1471-11ea-824b-a3dc49b4f1c1.png)

Could you share any information aimed at an additional double-check on my side?

2019-12-02 16:30 UTC, braindead-bf commented
It seems to be a compatibility issue with the Darwin version of bash. I had originally written the script to be compatible with GNU and Darwin versions; I'm not sure what broke in the upgrade. Do you have a Mac you can test on?

2019-12-04 19:43 UTC, bl4ckh0l3z commented
Yes, it’s a compatibility issue. The Darwin version of bash dislikes a switch case nested in a subshell; it’s an undocumented issue. I’ll do a fix and some tests...I will come back to you in a couple of days for the final merge.

2019-12-13 23:22 UTC, bl4ckh0l3z commented
Fixed and tested on macOS High Sierra 10.13...

2019-12-30 15:56 UTC, braindead-bf requested changes
Excellent - the code is functional on Mac now! A few more things before I'm ready to accept the changes:

- Bugfixes:
  - lines 85, 88, 95: add 0-9 to domain regex
  - lines 90, 104: change sed command to "sed -E 's/\\s/\\n/g'" (the need to double-backslash special characters might be a Darwin-specific issue)
  - line 99: fix typo in "already"
  - line 171: change sed command to "sed -E 's/(-----)(-----)/\1\\n\2/g'"
  - line 501: make formatting consistent with line 378

- Missing features:
  - Need the option to test cookies without downloading files
  - Vulnerability should not be determined by the version number, but by a failed download attempt
  - When a target is determined not to be vulnerable, a report should be produced indicating that

- Misc:
  - Add this line to the end of the comments section: "Huge thanks to bl4ckh0l3z for cleaning and refactoring the code significantly!"

2020-01-02 15:30 UTC, bl4ckh0l3z commented
# Bugfixes:
> lines 85, 88, 95: add 0-9 to domain regex

Done; the more correct regex "^[-\.a-zA-Z]+[0-9]*[-\.a-zA-Z]*$" was implemented; adding "0-9" to the current regex will catch too much, including IPs,
and fails the duplicate check at line #102 (based on reverse lookup)

> lines 90, 104: change sed command to "sed -E 's/\s/\n/g'" (the need to double-backslash special characters might be a Darwin-specific issue)

Cannot be applied because the "sed -E 's/\s/\n/g'" is already in place; please clarify.

> line 99: fix typo in "already"

Done.

> line 171: change sed command to "sed -E 's/(-----)(-----)/\1\n\2/g'"

Cannot be applied because the "sed -E 's/(-----)(-----)/\1\n\2/g'" is already in place; please clarify.

> line 501: make formatting consistent with line 378

Please clarify the meaning of "consistent"; #378 is the header for #501...the field are pretty the same and in the same order.

# Missing features:
> Need the option to test cookies without downloading files

Done; "-k" flag test cookies if they were already downloaded/extracted.

> Vulnerability should not be determined by the version number, but by a failed download attempt

Done.

> When a target is determined not to be vulnerable, a report should be produced indicating that

Done.

# Misc:
> Add this line to the end of the comments section: "Huge thanks to bl4ckh0l3z for cleaning and refactoring the code significantly!"

Done; I would be glad if you agree to change the thanks to "Huge thanks to @bl4ckh0l3z for fixes, cleaning and refactoring the code significantly!".

2020-01-02 16:14 UTC, braindead-bf commented
> # Bugfixes:
> > lines 85, 88, 95: add 0-9 to domain regex
> 
> Done; the more correct regex "^[-.a-zA-Z]+[0-9]_[-.a-zA-Z]_$" was implemented; adding "0-9" to the current regex will catch too much, including IPs, and fails the duplicate check at line #102 (based on reverse lookup)

Nice, good catch.

> > lines 90, 104: change sed command to "sed -E 's/\s/\n/g'" (the need to double-backslash special characters might be a Darwin-specific issue)
> 
> Cannot be applied because the "sed -E 's/\s/\n/g'" is already in place; please clarify.

Apologies - markdown modified what I pasted in: `sed -E 's/\\s/\\n/g'` (both \s and \n need to be double-escaped for them to work in my tests - probably a Darwin thing)

> > line 171: change sed command to "sed -E 's/(-----)(-----)/\1\n\2/g'"
> 
> Cannot be applied because the "sed -E 's/(-----)(-----)/\1\n\2/g'" is already in place; please clarify.

Same as above - double-escape the newline character: `sed -E 's/(-----)(-----)/\1\\n\2/g'`

> > line 501: make formatting consistent with line 378
> 
> Please clarify the meaning of "consistent"; #378 is the header for #501...the field are pretty the same and in the same order.

Maybe I misidentified which line needed to be fixed. In my test, the column spacing for the "Observed VPN Logins" section looked something like this:
```
Username                        Password              Name             Email
user1 p4ssw0rd
user2 s3cr3t
user3                           winter2019            User             user@domain.com
user4                           NeverLetUDown         Somebody         somebody@domain.com
```
I believe the passwords extracted from base64 aren't aligning with the rest.

> # Misc:
> > Add this line to the end of the comments section: "Huge thanks to bl4ckh0l3z for cleaning and refactoring the code significantly!"
> 
> Done; I would be glad if you agree to change the thanks to "Huge thanks to @bl4ckh0l3z for fixes, cleaning and refactoring the code significantly!".

Yep, sounds good.

2020-01-03 16:15 UTC, bl4ckh0l3z commented
# Bugfixes:
>>> lines 85, 88, 95: add 0-9 to domain regex

>> Done; the more correct regex "^[-\.a-zA-Z]+[0-9]*[-\.a-zA-Z]*$" was implemented; adding "0-9" to the current regex will catch too much, including IPs,
>> and fails the duplicate check at line #102 (based on reverse lookup)

> Nice, good catch.

Yep :)

>>> lines 90, 104: change sed command to "sed -E 's/\s/\n/g'" (the need to double-backslash special characters might be a Darwin-specific issue)

>> Cannot be applied because the "sed -E 's/\s/\n/g'" is already in place; please clarify.

> Apologies - markdown modified what I pasted in: sed -E 's/\\s/\\n/g' (both \s and \n need to be double-escaped for them to work in my tests - probably a Darwin thing)

Done. It's a Darwin issue; I also changed single-quotes to double-quotes in order to guarantee the execution in a linux env too.

>>> [...]

>>> line 171: change sed command to "sed -E 's/(-----)(-----)/\1\n\2/g'"

>> Cannot be applied because the "sed -E 's/(-----)(-----)/\1\n\2/g'" is already in place; please clarify.

> Same as above - double-escape the newline character: sed -E 's/(-----)(-----)/\1\\n\2/g'

Done.

>>> line 501: make formatting consistent with line 378

>> Please clarify the meaning of "consistent"; #378 is the header for #501...the field are pretty the same and in the same order.

> Maybe I misidentified which line needed to be fixed. In my test, the column spacing for the "Observed VPN Logins" section looked something like this:
> Username                        Password              Name             Email
> user1 p4ssw0rd
> user2 s3cr3t
> user3                           winter2019            User             user@domain.com
> user4                           NeverLetUDown         Somebody         somebody@domain.com
>
> I believe the passwords extracted from base64 aren't aligning with the rest.

Yes, it's true; fixed with minimal changes.

# Missing features:
>>> [...]

>>> [...]

>>> [...]

# Misc:
>>> Add this line to the end of the comments section: "Huge thanks to bl4ckh0l3z for cleaning and refactoring the code significantly!"

>> Done; I would be glad if you agree to change the thanks to "Huge thanks to bl4ckh0l3z for fixes, cleaning and refactoring the code significantly!".

> Yep, sounds good.

Thanks, I really appreciate.

2020-01-03 16:57 UTC, bl4ckh0l3z commented
@lines #143 and #144 there is just a minor improvement on checking if a device is vulnerable;
it's simple but very useful to avoid false positives when hosts provide 200 responses for any url
including https://${target}/dana-na/../dana/html5acc/guacamole/../../../../../../etc/passwd?/dana/html5acc/guacamole/.

2020-01-03 22:23 UTC, braindead-bf commented
Almost there! Unfortunately, the `sed` lines still aren't working - apparently Darwin requires them to use single quotes with double-backslashes (and even then, line 108 would still output a single line). Gah! Here's what I propose to simplify things: use `tr` instead of `sed` here.
```
94: target_list="$(echo ${target_list} | tr ' ' '\n' | sort -u)"
108: echo "  [+] Targets: #$(echo ${target_list} | tr ' ' '\n' | wc -l)" 
```
I also added double-quotes around the output of 94 to fix sorting (it wasn't working for me).

2020-01-10 19:56 UTC, bl4ckh0l3z commented
Sounds good and it works like a charm...
Lateral thinking: this is what I love!

2020-01-15 16:58 UTC, braindead-bf commented
We're good to go. Thank you again for all the hard work you put into this!

2020-01-15 16:58 UTC, merged

2020-01-15 19:13 UTC, bl4ckh0l3z commented
I’m happy to hear that; @braindead-bf thanks for your accurate and meticulous feedback. I’m looking forward to helping @BishopFox sooner or later in the future.